spring:
  profiles:
    active:
      - dev
---
server:
  port: 9101
eureka:
  client:
    register-with-eureka: false
    service-url:
      #defaultZone: http://admin:a@eureka3:7033/eureka,http://admin:a@eureka1:7031/eureka,http://admin:a@eureka2:7032/eureka
      defaultZone: http://admin:a@eureka1:7031/eureka
turbine:
  app-config: picweb1  #  配置Eureka中的serviceId列表，表明监控哪些服务, 启动后从配置中心中进行更新   有多个的话逗号分隔
  aggregator:
    cluster-config: default     #  指定聚合哪些集群，多个使用","分割，默认为default。
  cluster-name-expression: new String("default")   #表示集群的名字为default
  combine-host-port: true   
spring:
  application:
    name: base-microservice-hystrix-turbine
  profiles: beta 
 
 
