spring:
  profiles:
    active:
      - dev
---
server:
  port: 9101
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:a@eureka1:7033/eureka,http://admin:a@eureka2:7031/eureka,http://admin:a@eureka3:7032/eureka

turbine:
  app-config: piclibapi,piclibweb,piclibwap,userapi,userweb,userwap  #  配置Eureka中的serviceId列表，表明监控哪些服务, 启动后从配置中心中进行更新
  aggregator:
    cluster-config: default     #  指定聚合哪些集群，多个使用","分割，默认为default。
  cluster-name-expression: new String("default")   #表示集群的名字为default
  combine-host-port: true   
spring:
  application:
    name: base-microservice-hystrix-dashboard
  profiles: beta 
 
 
